# Generated by Django 4.2.3 on 2023-08-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cee', '0014_rename_post_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
